<?php

use Saccharine\BpmnEngine\Services\BpmnParserService;
use Saccharine\BpmnEngine\Models\WorkflowDefinition;
use Saccharine\BpmnEngine\Models\WorkflowNode;
use Saccharine\BpmnEngine\Models\WorkflowEdge;

it('parses a basic bpmn xml file into database nodes and edges', function () {
    // Scaffold a fake workflow definition and version in the database
    $definition = WorkflowDefinition::create([
        'name' => 'Test Process',
        'key'  => 'test-process',
    ]);
    
    $version = $definition->versions()->create([
        'version'   => 1,
        'bpmn_xml'  => '<xml>fake</xml>',
        'is_active' => true,
    ]);

    // A minimal, valid BPMN 2.0 XML string generated by bpmn-js
    $xmlString = <<<XML
    <?xml version="1.0" encoding="UTF-8"?>
    <bpmn:definitions xmlns:bpmn="http://omg.org/spec/BPMN/20100524/MODEL" xmlns:camunda="http://camunda.org/schema/1.0/bpmn" id="Definitions_1">
      <bpmn:process id="Process_1" isExecutable="true">
        <bpmn:startEvent id="StartEvent_1">
          <bpmn:outgoing>Flow_1</bpmn:outgoing>
        </bpmn:startEvent>
        <bpmn:serviceTask id="Task_ChargeCard" name="Charge Credit Card" camunda:class="charge_credit_card">
          <bpmn:incoming>Flow_1</bpmn:incoming>
        </bpmn:serviceTask>
        <bpmn:sequenceFlow id="Flow_1" sourceRef="StartEvent_1" targetRef="Task_ChargeCard" />
      </bpmn:process>
    </bpmn:definitions>
    XML;

    // Execute the parser
    $parser = new BpmnParserService();
    $parser->parseAndStore($version, $xmlString);

    // Assert the database state is correct
    // We expect exactly two nodes (Start Event, Service Task)
    expect(WorkflowNode::count())->toBe(2);
    
    // We expect exactly one connecting arrow (Sequence Flow)
    expect(WorkflowEdge::count())->toBe(1);

    // Verify the custom Camunda attribute was mapped properly
    $taskNode = WorkflowNode::where('type', 'serviceTask')->first();
    expect($taskNode->bpmn_element_id)->toBe('Task_ChargeCard')
        ->and($taskNode->implementation)->toBe('charge_credit_card');
});

it('throws an exception when parsing completely malformed xml', function () {
    $definition = WorkflowDefinition::create([
        'name' => 'Malformed XML',
        'key'  => 'malformed-xml',
    ]);
    
    $version = $definition->versions()->create([
        'version'   => 1,
        'bpmn_xml'  => '<xml>fake</xml>',
        'is_active' => true,
    ]);

    // A string that is completely invalid XML syntax
    $xmlString = "This is just a random string, not XML.";

    $parser = new BpmnParserService();
    
    // SimpleXMLElement throws a generic Exception when it fails to parse
    $parser->parseAndStore($version, $xmlString);
})->throws(Exception::class);


it('throws an exception when the xml lacks a process element', function () {
    $definition = WorkflowDefinition::create([
        'name' => 'No Process XML',
        'key'  => 'no-process-xml',
    ]);
    
    $version = $definition->versions()->create([
        'version'   => 1,
        'bpmn_xml'  => '<xml>fake</xml>',
        'is_active' => true,
    ]);

    // Structurally valid XML, but missing the <bpmn:process> block
    $xmlString = <<<XML
    <?xml version="1.0" encoding="UTF-8"?>
    <bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" id="Definitions_1">
      <!-- Missing bpmn:process here -->
    </bpmn:definitions>
    XML;

    $parser = new BpmnParserService();
    $parser->parseAndStore($version, $xmlString);
})->throws(Exception::class, 'Invalid BPMN file: <bpmn:process> element not found.');


it('throws an exception if the standard BPMN namespace is incorrect', function () {
    $definition = WorkflowDefinition::create([
        'name' => 'Bad Namespace',
        'key'  => 'bad-namespace',
    ]);
    
    $version = $definition->versions()->create([
        'version'   => 1,
        'bpmn_xml'  => '<xml>fake</xml>',
        'is_active' => true,
    ]);

    // The process block exists, but the namespace xmlns:bpmn is completely wrong.
    $xmlString = <<<XML
    <?xml version="1.0" encoding="UTF-8"?>
    <bpmn:definitions xmlns:bpmn="http://wrong-url.org/MODEL" id="Definitions_1">
      <bpmn:process id="Process_1" isExecutable="true">
        <bpmn:startEvent id="StartEvent_1" />
      </bpmn:process>
    </bpmn:definitions>
    XML;

    $parser = new BpmnParserService();
    $parser->parseAndStore($version, $xmlString);
})->throws(\Exception::class, 'Invalid BPMN file: Incorrect or missing BPMN namespace URI.');

it('throws an exception if the //bpmn:process block is not found', function () {
    $definition = WorkflowDefinition::create([
        'name' => 'Missing Process',
        'key'  => 'missing-process',
    ]);
    
    $version = $definition->versions()->create([
        'version'   => 1,
        'bpmn_xml'  => '<xml>fake</xml>',
        'is_active' => true,
    ]);

    // The process block exists, but the namespace xmlns:bpmn is completely wrong.
    // The XPath '//bpmn:process' will fail to find it.
    $xmlString = <<<XML
    <?xml version="1.0" encoding="UTF-8"?>
    <bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" id="Definitions_1">
    </bpmn:definitions>
    XML;

    $parser = new BpmnParserService();
    $parser->parseAndStore($version, $xmlString);
})->throws(\Exception::class, 'Invalid BPMN file: <bpmn:process> element not found.');

it('parses a call activity and extracts the calledElement attribute as its implementation', function () {
    $definition = \Saccharine\BpmnEngine\Models\WorkflowDefinition::create([
        'name' => 'Caller Process',
        'key'  => 'caller-process',
    ]);
    
    $version = $definition->versions()->create([
        'version'   => 1,
        'bpmn_xml'  => '<xml>fake</xml>',
        'is_active' => true,
    ]);

    // A minimal XML string featuring a callActivity
    $xmlString = <<<XML
    <?xml version="1.0" encoding="UTF-8"?>
    <bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" id="Definitions_1">
      <bpmn:process id="Process_1" isExecutable="true">
        <bpmn:callActivity id="CallActivity_1" name="Process Billing" calledElement="billing-process" />
      </bpmn:process>
    </bpmn:definitions>
    XML;

    $parser = new \Saccharine\BpmnEngine\Services\BpmnParserService();
    $parser->parseAndStore($version, $xmlString);

    $callNode = \Saccharine\BpmnEngine\Models\WorkflowNode::where('type', 'callActivity')->first();
    
    expect($callNode)->not->toBeNull()
        ->and($callNode->bpmn_element_id)->toBe('CallActivity_1')
        ->and($callNode->implementation)->toBe('billing-process'); // Maps to calledElement
});

it('parses an inline sub-process and assigns a parent_element_id to its internal children', function () {
    $definition = \Saccharine\BpmnEngine\Models\WorkflowDefinition::create([
        'name' => 'SubProcess Process',
        'key'  => 'subprocess-process',
    ]);
    
    $version = $definition->versions()->create([
        'version'   => 1,
        'bpmn_xml'  => '<xml>fake</xml>',
        'is_active' => true,
    ]);

    // A minimal XML string featuring an inline subProcess and internal nodes
    $xmlString = <<<XML
    <?xml version="1.0" encoding="UTF-8"?>
    <bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:camunda="http://camunda.org/schema/1.0/bpmn" id="Definitions_1">
      <bpmn:process id="Process_1" isExecutable="true">
        <bpmn:subProcess id="SubProcess_1" name="Grouped Tasks">
          <bpmn:startEvent id="SubStart_1" />
          <bpmn:serviceTask id="SubTask_1" name="Internal Action" camunda:class="internal_action" />
          <bpmn:endEvent id="SubEnd_1" />
          <bpmn:sequenceFlow id="Flow_S1" sourceRef="SubStart_1" targetRef="SubTask_1" />
          <bpmn:sequenceFlow id="Flow_S2" sourceRef="SubTask_1" targetRef="SubEnd_1" />
        </bpmn:subProcess>
      </bpmn:process>
    </bpmn:definitions>
    XML;

    $parser = new \Saccharine\BpmnEngine\Services\BpmnParserService();
    $parser->parseAndStore($version, $xmlString);

    // Verify the subProcess node itself was created
    $subProcessNode = \Saccharine\BpmnEngine\Models\WorkflowNode::where('type', 'subProcess')->first();
    expect($subProcessNode)->not->toBeNull()
        ->and($subProcessNode->bpmn_element_id)->toBe('SubProcess_1');

    // Verify the internal tasks were created and scoped to the parent subProcess
    $internalTask = \Saccharine\BpmnEngine\Models\WorkflowNode::where('bpmn_element_id', 'SubTask_1')->first();
    
    expect($internalTask)->not->toBeNull()
        ->and($internalTask->type)->toBe('serviceTask')
        ->and($internalTask->parent_element_id)->toBe('SubProcess_1');
});