<?php

use MatthewWegner\BpmnEngine\Services\BpmnParserService;
use MatthewWegner\BpmnEngine\Models\WorkflowDefinition;
use MatthewWegner\BpmnEngine\Models\WorkflowNode;
use MatthewWegner\BpmnEngine\Models\WorkflowEdge;

it('parses a basic bpmn xml file into database nodes and edges', function () {
    // Scaffold a fake workflow definition and version in the database
    $definition = WorkflowDefinition::create([
        'name' => 'Test Process',
        'key'  => 'test-process',
    ]);
    
    $version = $definition->versions()->create([
        'version'   => 1,
        'bpmn_xml'  => '<xml>fake</xml>',
        'is_active' => true,
    ]);

    // A minimal, valid BPMN 2.0 XML string generated by bpmn-js
    $xmlString = <<<XML
    <?xml version="1.0" encoding="UTF-8"?>
    <bpmn:definitions xmlns:bpmn="http://omg.org/spec/BPMN/20100524/MODEL" xmlns:camunda="http://camunda.org/schema/1.0/bpmn" id="Definitions_1">
      <bpmn:process id="Process_1" isExecutable="true">
        <bpmn:startEvent id="StartEvent_1">
          <bpmn:outgoing>Flow_1</bpmn:outgoing>
        </bpmn:startEvent>
        <bpmn:serviceTask id="Task_ChargeCard" name="Charge Credit Card" camunda:class="charge_credit_card">
          <bpmn:incoming>Flow_1</bpmn:incoming>
        </bpmn:serviceTask>
        <bpmn:sequenceFlow id="Flow_1" sourceRef="StartEvent_1" targetRef="Task_ChargeCard" />
      </bpmn:process>
    </bpmn:definitions>
    XML;

    // Execute the parser
    $parser = new BpmnParserService();
    $parser->parseAndStore($version, $xmlString);

    // Assert the database state is correct
    // We expect exactly two nodes (Start Event, Service Task)
    expect(WorkflowNode::count())->toBe(2);
    
    // We expect exactly one connecting arrow (Sequence Flow)
    expect(WorkflowEdge::count())->toBe(1);

    // Verify the custom Camunda attribute was mapped properly
    $taskNode = WorkflowNode::where('type', 'serviceTask')->first();
    expect($taskNode->bpmn_element_id)->toBe('Task_ChargeCard')
        ->and($taskNode->implementation)->toBe('charge_credit_card');
});