name: Run Tests

on:
    push:
        branches: [ main, master, develop ]
    pull_request:
        branches: [ main, master, develop ]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: ['8.2', '8.3', '8.4']
                laravel: ['11.0', '12.0', '13.0']
                stability: [prefer-stable]
                include:
                  - laravel: '11.0'
                    testbench: '9.0'
                  - laravel: '12.0'
                    testbench: '10.0'
                  - laravel: '13.0'
                    testbench: '11.0'
                exclude:
                  - php: '8.2'
                    laravel: '13.0'

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php }}
                extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
                coverage: none

            - name: Install Laravel Orchestral Testbench
              run: |
                composer require "orchestra/testbench=^${{ matrix.testbench }}" --dev --no-interaction --no-update

            - name: Install dependencies
              run: |
                composer update --${{ matrix.stability }} --prefer-dist --no-interaction

            - name: Execute tests
              run: vendor/bin/pest